# Site Settings
title: "Moshiur Rahman | Academic Portfolio"
email: moshiur.rahman.252@northsouth.edu
description: >-
  Academic portfolio of Moshiur Rahman, M.S. Candidate in Applied Mathematics & Computational Science 
  at North South University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from the build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/